{"pageProps":{"page":{"slug":"class.assertionerror.md","content":"# AssertionError\n\n(PHP 7, PHP 8)\n\n## Вступ\n\n**AssertionError** викидається, коли твердження, зроблене за допомогою [assert()](function.assert.md), зазнає невдачі.\n\n## Огляд класів\n\n```classsynopsis\n\n     \n      class AssertionError\n     \n\n     \n      extends\n       Error\n      {\n\n     /* Наследуемые свойства */\n     \n     protected\n     string\n      $message = \"\";\nprivate\n     string\n      $string = \"\";\nprotected\n     int\n      $code;\nprotected\n     string\n      $file = \"\";\nprotected\n     int\n      $line;\nprivate\n     array\n      $trace = [];\nprivate\n     ?Throwable\n      $previous = null;\n\n\n     /* Наследуемые методы */\n     \n   public Error::__construct(string $message = \"\", int $code = 0, ?Throwable $previous = null)\n\n     final public Error::getMessage(): string\nfinal public Error::getPrevious(): ?Throwable\nfinal public Error::getCode(): int\nfinal public Error::getFile(): string\nfinal public Error::getLine(): int\nfinal public Error::getTrace(): array\nfinal public Error::getTraceAsString(): string\npublic Error::__toString(): string\nprivate Error::__clone(): void\n\n    }\n```\n","title":"AssertionError","contentType":2,"navigation":[{"class.arithmeticerror.md":"« ArithmeticError"},{"class.divisionbyzeroerror.md":"DivisionByZeroError »"},{"index.md":"PHP Manual"},{"reserved.exceptions.md":"Обумовлені винятки"}]}},"__N_SSG":true}