{"pageProps":{"page":{"slug":"exception.getprevious.md","content":"# Exception::getPrevious\n\n(PHP 5 >= 5.3.0, PHP 7, PHP 8)\n\nException::getPrevious — Повертає попередній об'єкт, що реалізує Throwable\n\n### Опис\n\n```methodsynopsis\nfinal public Exception::getPrevious(): ?Throwable\n```\n\nПовертає попередній об'єкт, що реалізує [Throwable](class.throwable.md) (переданий третім параметром [Exception::\\_\\_construct()](exception.construct.md)\n\n### Список параметрів\n\nЦя функція не має параметрів.\n\n### Значення, що повертаються\n\nПовертає попередній об'єкт, що реалізує [Throwable](class.throwable.md)или\\*\\*`null`\\*\\*якщо такого немає.\n\n### Приклади\n\n**Приклад #1 Приклад використання** Exception::getPrevious()\\*\\*\\*\\*\n\nПрохід та друк ланцюга винятків.\n\n```php\n<?php\nclass MyCustomException extends Exception {}\n\nfunction doStuff() {\n    try {\n        throw new InvalidArgumentException(\"Ты делаешь это неправильно!\", 112);\n    } catch(Exception $e) {\n        throw new MyCustomException(\"Что-то случилось\", 911, $e);\n    }\n}\n\n\ntry {\n    doStuff();\n} catch(Exception $e) {\n    do {\n        printf(\"%s:%d %s (%d) [%s]\\n\", $e->getFile(), $e->getLine(), $e->getMessage(), $e->getCode(), get_class($e));\n    } while($e = $e->getPrevious());\n}\n?>\n```\n\nВисновок наведеного прикладу буде схожим на:\n\n```\n/home/bjori/ex.php:8 Что-то случилось (911) [MyCustomException]\n/home/bjori/ex.php:6 Ты делаешь это неправильно! (112) [InvalidArgumentException]\n```\n\n### Дивіться також\n\n-   [Throwable::getPrevious()](throwable.getprevious.md) \\- Повертає попередній Throwable\n","title":"Exception::getPrevious","contentType":2,"navigation":[{"exception.getmessage.md":"« Exception::getMessage"},{"exception.getcode.md":"Exception::getCode »"},{"index.md":"PHP Manual"},{"class.exception.md":"Exception"}]}},"__N_SSG":true}